/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as InternalImport } from './routes/_internal'
import { Route as AuthImport } from './routes/_auth'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as InternalCompanyImport } from './routes/_internal/company'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as InternalJobsIndexImport } from './routes/_internal/jobs/index'
import { Route as InternalJobsCreateImport } from './routes/_internal/jobs/create'
import { Route as LayoutSearchJobsIndexImport } from './routes/_layout/search/jobs/index'
import { Route as LayoutSearchCompaniesIndexImport } from './routes/_layout/search/companies/index'
import { Route as LayoutSearchJobsJobIdImport } from './routes/_layout/search/jobs/$jobId'
import { Route as LayoutSearchCompaniesCompanyIdImport } from './routes/_layout/search/companies/$companyId'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const InternalRoute = InternalImport.update({
  id: '/_internal',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const InternalCompanyRoute = InternalCompanyImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => InternalRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const InternalJobsIndexRoute = InternalJobsIndexImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => InternalRoute,
} as any)

const InternalJobsCreateRoute = InternalJobsCreateImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => InternalRoute,
} as any)

const LayoutSearchJobsIndexRoute = LayoutSearchJobsIndexImport.update({
  id: '/search/jobs/',
  path: '/search/jobs/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchCompaniesIndexRoute = LayoutSearchCompaniesIndexImport.update(
  {
    id: '/search/companies/',
    path: '/search/companies/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutSearchJobsJobIdRoute = LayoutSearchJobsJobIdImport.update({
  id: '/search/jobs/$jobId',
  path: '/search/jobs/$jobId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchCompaniesCompanyIdRoute =
  LayoutSearchCompaniesCompanyIdImport.update({
    id: '/search/companies/$companyId',
    path: '/search/companies/$companyId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_internal': {
      id: '/_internal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof InternalImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_internal/company': {
      id: '/_internal/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof InternalCompanyImport
      parentRoute: typeof InternalImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_internal/jobs/create': {
      id: '/_internal/jobs/create'
      path: '/jobs/create'
      fullPath: '/jobs/create'
      preLoaderRoute: typeof InternalJobsCreateImport
      parentRoute: typeof InternalImport
    }
    '/_internal/jobs/': {
      id: '/_internal/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof InternalJobsIndexImport
      parentRoute: typeof InternalImport
    }
    '/_layout/search/companies/$companyId': {
      id: '/_layout/search/companies/$companyId'
      path: '/search/companies/$companyId'
      fullPath: '/search/companies/$companyId'
      preLoaderRoute: typeof LayoutSearchCompaniesCompanyIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/jobs/$jobId': {
      id: '/_layout/search/jobs/$jobId'
      path: '/search/jobs/$jobId'
      fullPath: '/search/jobs/$jobId'
      preLoaderRoute: typeof LayoutSearchJobsJobIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/companies/': {
      id: '/_layout/search/companies/'
      path: '/search/companies'
      fullPath: '/search/companies'
      preLoaderRoute: typeof LayoutSearchCompaniesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/jobs/': {
      id: '/_layout/search/jobs/'
      path: '/search/jobs'
      fullPath: '/search/jobs'
      preLoaderRoute: typeof LayoutSearchJobsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface InternalRouteChildren {
  InternalCompanyRoute: typeof InternalCompanyRoute
  InternalJobsCreateRoute: typeof InternalJobsCreateRoute
  InternalJobsIndexRoute: typeof InternalJobsIndexRoute
}

const InternalRouteChildren: InternalRouteChildren = {
  InternalCompanyRoute: InternalCompanyRoute,
  InternalJobsCreateRoute: InternalJobsCreateRoute,
  InternalJobsIndexRoute: InternalJobsIndexRoute,
}

const InternalRouteWithChildren = InternalRoute._addFileChildren(
  InternalRouteChildren,
)

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSearchCompaniesCompanyIdRoute: typeof LayoutSearchCompaniesCompanyIdRoute
  LayoutSearchJobsJobIdRoute: typeof LayoutSearchJobsJobIdRoute
  LayoutSearchCompaniesIndexRoute: typeof LayoutSearchCompaniesIndexRoute
  LayoutSearchJobsIndexRoute: typeof LayoutSearchJobsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSearchCompaniesCompanyIdRoute: LayoutSearchCompaniesCompanyIdRoute,
  LayoutSearchJobsJobIdRoute: LayoutSearchJobsJobIdRoute,
  LayoutSearchCompaniesIndexRoute: LayoutSearchCompaniesIndexRoute,
  LayoutSearchJobsIndexRoute: LayoutSearchJobsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/company': typeof InternalCompanyRoute
  '/': typeof LayoutIndexRoute
  '/jobs/create': typeof InternalJobsCreateRoute
  '/jobs': typeof InternalJobsIndexRoute
  '/search/companies/$companyId': typeof LayoutSearchCompaniesCompanyIdRoute
  '/search/jobs/$jobId': typeof LayoutSearchJobsJobIdRoute
  '/search/companies': typeof LayoutSearchCompaniesIndexRoute
  '/search/jobs': typeof LayoutSearchJobsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof InternalRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/company': typeof InternalCompanyRoute
  '/': typeof LayoutIndexRoute
  '/jobs/create': typeof InternalJobsCreateRoute
  '/jobs': typeof InternalJobsIndexRoute
  '/search/companies/$companyId': typeof LayoutSearchCompaniesCompanyIdRoute
  '/search/jobs/$jobId': typeof LayoutSearchJobsJobIdRoute
  '/search/companies': typeof LayoutSearchCompaniesIndexRoute
  '/search/jobs': typeof LayoutSearchJobsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_internal': typeof InternalRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_internal/company': typeof InternalCompanyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_internal/jobs/create': typeof InternalJobsCreateRoute
  '/_internal/jobs/': typeof InternalJobsIndexRoute
  '/_layout/search/companies/$companyId': typeof LayoutSearchCompaniesCompanyIdRoute
  '/_layout/search/jobs/$jobId': typeof LayoutSearchJobsJobIdRoute
  '/_layout/search/companies/': typeof LayoutSearchCompaniesIndexRoute
  '/_layout/search/jobs/': typeof LayoutSearchJobsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/company'
    | '/'
    | '/jobs/create'
    | '/jobs'
    | '/search/companies/$companyId'
    | '/search/jobs/$jobId'
    | '/search/companies'
    | '/search/jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/register'
    | '/company'
    | '/'
    | '/jobs/create'
    | '/jobs'
    | '/search/companies/$companyId'
    | '/search/jobs/$jobId'
    | '/search/companies'
    | '/search/jobs'
  id:
    | '__root__'
    | '/_auth'
    | '/_internal'
    | '/_layout'
    | '/_auth/login'
    | '/_auth/register'
    | '/_internal/company'
    | '/_layout/'
    | '/_internal/jobs/create'
    | '/_internal/jobs/'
    | '/_layout/search/companies/$companyId'
    | '/_layout/search/jobs/$jobId'
    | '/_layout/search/companies/'
    | '/_layout/search/jobs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  InternalRoute: typeof InternalRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  InternalRoute: InternalRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_internal",
        "/_layout"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/register"
      ]
    },
    "/_internal": {
      "filePath": "_internal.tsx",
      "children": [
        "/_internal/company",
        "/_internal/jobs/create",
        "/_internal/jobs/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/search/companies/$companyId",
        "/_layout/search/jobs/$jobId",
        "/_layout/search/companies/",
        "/_layout/search/jobs/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_internal/company": {
      "filePath": "_internal/company.tsx",
      "parent": "/_internal"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_internal/jobs/create": {
      "filePath": "_internal/jobs/create.tsx",
      "parent": "/_internal"
    },
    "/_internal/jobs/": {
      "filePath": "_internal/jobs/index.tsx",
      "parent": "/_internal"
    },
    "/_layout/search/companies/$companyId": {
      "filePath": "_layout/search/companies/$companyId.tsx",
      "parent": "/_layout"
    },
    "/_layout/search/jobs/$jobId": {
      "filePath": "_layout/search/jobs/$jobId.tsx",
      "parent": "/_layout"
    },
    "/_layout/search/companies/": {
      "filePath": "_layout/search/companies/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/search/jobs/": {
      "filePath": "_layout/search/jobs/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
